# Generated by Django 5.2.17 on 2026-09-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('create_article', 'Permission for a User to create an Article'), ('update_article', 'Permission for a user to edit an article')]},
        ),
    ]
