# Generated by Django 5.2.17 on 2026-09-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('create_article', 'Permission for a User to create an Article'), ('update_article', 'Permission for a user to edit an article'), ('dummp_perm', 'Dummy Perm')]},
        ),
    ]
