# Generated by Django 5.2.17 on 2026-09-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
