# Generated by Django 5.2.17 on 2026-09-16 16:25

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
            ],
            options={
                'permissions': [('create_article', 'User can create article'), ('edit_article', 'Edit Article')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
            ],
            options={
                'permissions': [('edit_article', 'Edit Article')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
