# Generated by Django 5.2.17 on 2026-09-16 16:27

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blog', '0006_author_publisher'), ('blog', '0007_alter_article_author')]

    dependencies = [
        ('blog', '0005_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
            ],
            options={
                'permissions': [('create_article', 'User can create article'), ('edit_article', 'Edit Article')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
            ],
            options={
                'permissions': [('edit_article', 'Edit Article')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
    ]
